import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Socials",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0C0C0C]">
      <h1 className="px-20 py-10 text-[#09846E] text-2xl font-bold">Socials.</h1>
        {children}
      </body>
    </html>
  );
}
